//
//  SumberData.swift
//  ADA Kantin
//
//  Created by Daven Karim on 09/04/25.
//

import Foundation

struct TenantData {
    static let allTenants: [TenantItem] = [
        TenantItem(id: 1,
                   name: "Soto Pak Gembul",
                   image: "sotopakgembul_img",
                   logo: "soto pak gembul logo",
                   minPrice: 18000,
                   maxPrice: 30000,
                   tags: ["kategori.Ayam", "kategori.Sapi", "kategori.Cabe", "kategori.Sayur"],
                   description: "Soto lezat dengan kuah gurih dan daging empuk.",
                   foodItems: [
                    FoodItem(name: "Soto Ayam",
                             price: 23000,
                             image: "soto.ayam.pakgembul",
                             tags: ["kategori.Ayam", "kategori.Sayur"],
                             location: "Soto Pak Gembul",
                             foodDescription: "Soto ayam lezat buatan Pak Gembul",
                             tenantId: 1)
                   ]),
        TenantItem(id: 3,
                   name: "Kedai 2 Nyonya",
                   image: "kedai2nyonya_img",
                   logo: "kedai dua nyonya logo",
                   minPrice: 2000,
                   maxPrice: 25000,
                   tags: ["kategori.Ayam", "kategori.Sapi", "kategori.Ikan", "kategori.Cabe", "kategori.Sayur"],
                   description: "Masakan rumahan ala nyonya, nikmat dan mengenyangkan.",
                   foodItems: [
                    FoodItem(name: "Nasi Bogana",
                             price: 25000,
                             image: "nasi.bogana",
                             tags: ["kategori.Ayam", "kategori.Sayur"],
                             location: "Kedai 2 Nyonya",
                             foodDescription: "Nasi bogana yang lezat buatan Kedai 2 Nyonya",
                             tenantId: 3),
                    FoodItem(name: "Nasi Krawu",
                             price: 25000,
                             image: "Nasi Krawu",
                             tags: ["kategori.Ayam"],
                             location: "Kedai 2 Nyonya",
                             foodDescription: "Nasi Krawu yang lezat buatan Kedai 2 Nyonya",
                             tenantId: 3),
                    FoodItem(name: "Nasi Pecel",
                             price: 20000,
                             image: "Nasi Pecel",
                             tags: ["kategori.Ayam", "kategori.Sayur"],
                             location: "Kedai 2 Nyonya",
                             foodDescription: "Nasi Pecel yang lezat buatan Kedai 2 Nyonya",
                             tenantId: 3),
                    FoodItem(name: "Nasi Tempong",
                             price: 22000,
                             image: "Nasi Tempong",
                             tags: ["kategori.Ayam", "kategori.Sayur"],
                             location: "Kedai 2 Nyonya",
                             foodDescription: "Nasi Tempong yang lezat buatan Kedai 2 Nyonya",
                             tenantId: 3),
                    FoodItem(name: "Aneka Gorengan",
                             price: 2000,
                             image: "Aneka Gorengan",
                             tags: ["kategori.Ayam", "kategori.Sayur"],
                             location: "Kedai 2 Nyonya",
                             foodDescription: "Aneka Gorengan  yang lezat buatan Kedai 2 Nyonya",
                             tenantId: 3)
                   ]),
        TenantItem(id: 4,
                   name: "Bebek Goreng Rinjani",
                   image: "bebekgorengrinjani_img",
                   logo: "bebek rinjani logo",
                   minPrice: 23000,
                   maxPrice: 35000,
                   tags: ["kategori.Ayam", "kategori.Cabe"],
                   description: "Bebek goreng krispi dengan bumbu khas Rinjani.",
                   foodItems: [
                    FoodItem(name: "Bebek Goreng",
                             price: 23000,
                             image: "bebek.goreng.rinjani",
                             tags: ["kategori.Ayam", "kategori.Cabe"],
                             location: "Bebek Goreng Rinjani",
                             foodDescription: "Bebek goreng krispi dengan bumbu khas Rinjani",
                             tenantId: 4)
                   ]),
        TenantItem(id: 5,
                   name: "Kantin Kasturi",
                   image: "kantinkasturi_img",
                   logo: "kasturi.logo",
                   minPrice: 15000,
                   maxPrice: 25000,
                   tags: ["kategori.Ayam", "kategori.Sapi", "kategori.Ikan", "kategori.Cabe", "kategori.Sayur"],
                   description: "Hidangan sederhana dengan rasa yang memikat.",
                   foodItems: [
                    FoodItem(name: "Ayam Bistik",
                             price: 7000,
                             image: "ayam.bistik",
                             tags: [ "kategori.Ayam"],
                             location: "Kantin Kasturi",
                             foodDescription: "Potongan ayam empuk dipanggang atau digoreng dengan sempurna, disajikan dengan saus bistik khas yang manis-gurih, ditambah irisan bawang bombay dan paprika untuk cita rasa yang kaya. Cocok dinikmati dengan nasi hangat atau kentang tumbuk.",
                             tenantId: 5),
                    FoodItem(name: "Cah Toge",
                             price: 3000,
                             image: "cah.toge",
                             tags: ["kategori.Sayur", "kategori.Cabe"],
                             location: "Kantin Kasturi",
                             foodDescription: "Toge segar yang ditumis dengan bawang putih, cabai, dan bumbu rahasia kami. Hidangan sederhana namun penuh nutrisi dan rasa.",
                             tenantId: 5),
                    FoodItem(name: "Ayam Teriyaki",
                             price: 7000,
                             image: "ayam.teriyaki",
                             tags: ["kategori.Ayam"],
                             location: "Kantin Kasturi",
                             foodDescription: "Ayam premium yang dimarinasi dengan saus teriyaki khas, dipanggang hingga kecokelatan dan disajikan dengan taburan wijen. Rasa manis-gurih yang seimbang.",
                             tenantId: 5),
                    FoodItem(name: "Ikan Cabe Garam",
                             price: 8000,
                             image: "ikan.cabe.garam",
                             tags: ["kategori.Ikan", "kategori.Cabe"],
                             location: "Kantin Kasturi",
                             foodDescription: "Ikan segar yang digoreng krispi lalu ditumis dengan cabai dan bawang putih. Pedas gurih yang menggugah selera.",
                             tenantId: 5),
                    FoodItem(name: "Ayam Geprek",
                             price: 17000,
                             image: "ayam.geprek",
                             tags: ["kategori.Ayam", "kategori.Cabe"],
                             location: "Kantin Kasturi",
                             foodDescription: "Ayam krispi ala geprek dengan sambal bawang yang pedasnya pas. Daging ayam yang juicy dengan lapisan tepung yang renyah.",
                             tenantId: 5),
                    FoodItem(name: "Ayam Penyet",
                             price: 17000,
                             image: "ayam.penyet",
                             tags: ["kategori.Ayam", "kategori.Cabe"],
                             location: "Kantin Kasturi",
                             foodDescription: "Ayam kampung yang dimasak dengan bumbu rempah khas, disajikan dengan sambal terasi yang pedas menggigit.",
                             tenantId: 5),
                    FoodItem(name: "Sosis Oseng",
                             price: 7000,
                             image: "sosis.oseng",
                             tags: ["kategori.Sapi", "kategori.Cabe"],
                             location: "Kantin Kasturi",
                             foodDescription: "Sosis premium yang dioseng dengan bawang bombay, cabai, dan bumbu spesial. Cocok untuk teman nasi hangat.",
                             tenantId: 5),
                    FoodItem(name: "Tempe Orek",
                             price: 3500,
                             image: "tempe.orek",
                             tags: ["kategori.Sayur"],
                             location: "Kantin Kasturi",
                             foodDescription: "Tempe yang diiris tipis dan digoreng kering dengan bumbu manis pedas. Kriuk-kriuk yang bikin ketagihan.",
                             tenantId: 5),
                    FoodItem(name: "Sapi Lada Hitam",
                             price: 8000,
                             image: "sapi.lada.hitam",
                             tags: ["kategori.Sapi", "kategori.Cabe"],
                             location: "Kantin Kasturi",
                             foodDescription: "Daging sapi pilihan yang ditumis dengan lada hitam, bawang bombay, dan paprika. Gurih dan sedikit pedas.",
                             tenantId: 5),
                    FoodItem(name: "Telur Dadar",
                             price: 3000,
                             image: "telur.dadar",
                             tags: ["kategori.Sayur"],
                             location: "Kantin Kasturi",
                             foodDescription: "Telur dadar tebal dengan isian daun bawang dan bumbu rahasia. Sederhana tapi selalu memuaskan.",
                             tenantId: 5)
                   ]),
        TenantItem(id: 6,
                   name: "La Ding",
                   image: "lading_img",
                   logo: "la ding logo",
                   minPrice: 18000,
                   maxPrice: 30000,
                   tags: ["kategori.Sayur", "kategori.Kacang"],
                   description: "Menjual soto dan siomay enak, cocok untuk makan siang.",
                   foodItems: [
                    FoodItem(name: "Telur Dadar La ding",
                             price: 5000,
                             image: "telur.dadar.lading",
                             tags: ["kategori.Sayur"],
                             location: "La Ding",
                             foodDescription: "Telur dadar renyah dan lezat buatan La Ding.",
                             tenantId: 6),
                    FoodItem(name: "Gado-Gado la ding",
                             price: 18000,
                             image: "gado.gado",
                             tags: ["kategori.Sayur", "kategori.Kacang"],
                             location: "La Ding",
                             foodDescription: "Campuran sayuran segar dengan bumbu kacang khas yang gurih. Disajikan dengan kerupuk dan telur rebus.",
                             tenantId: 6)
                   ]),
        TenantItem(id: 7,
                   name: "Kedai Laris",
                   image: "kedailaris_img",
                   logo: "laris manis logo",
                   minPrice: 18000,
                   maxPrice: 35000,
                   tags: ["kategori.Ayam", "kategori.Sapi", "kategori.Ikan", "kategori.Cabe", "kategori.Sayur"],
                   description: "Pilihan menu yang selalu laris dan favorit pelanggan.",
                   foodItems: [
                    FoodItem(name: "Ayam Madu",
                             price: 8500,
                             image: "ayam.madu",
                             tags: [ "kategori.Ayam"],
                             location: "Kedai Laris",
                             foodDescription: "Ayam madu yang dagingnya berkualitas dan segar buatan Kedai Laris.",
                             tenantId: 7)
                   ]),
        TenantItem(id: 8,
                   name: "Kedai Khas Nusantara",
                   image: "kedaikhasnusantara_img",
                   logo: "kedai khas nusantara logo",
                   minPrice: 18000,
                   maxPrice: 25000,
                   tags: ["kategori.Ayam", "kategori.Sapi", "kategori.Ikan", "kategori.Cabe", "kategori.Sayur"],
                   description: "Menyajikan kuliner tradisional dari berbagai daerah di Indonesia.",
                   foodItems: [
                    FoodItem(name: "Ayam Mentega",
                             price: 5000,
                             image: "ayam.mentega",
                             tags: [ "kategori.Ayam"],
                             location: "Kedai Khas Nusantara",
                             foodDescription: "Ayam mentega yang dagingnya berkualitas dan segar buatan Kedai Khas Nusantara.",
                             tenantId: 8)
                   ]),
        TenantItem(id: 9,
                   name: "Dapoer Cowek",
                   image: "dapoercowek_img",
                   logo: "dapoer cowek logo",
                   minPrice: 15000,
                   maxPrice: 30000,
                   tags: ["kategori.Ayam", "kategori.Sapi", "kategori.Ikan", "kategori.Cabe", "kategori.Sayur"],
                   description: "Masakan rumahan autentik dengan sentuhan bumbu cowek khas.",
                   foodItems: [
                    FoodItem(name: "Ayam Sambal Ijo",
                             price: 7000,
                             image: "ayam.ijo",
                             tags: [ "kategori.Ayam"],
                             location: "Dapoer Cowek",
                             foodDescription: "Ayam sambal ijo yang dagingnya berkualitas dan segar buatan Dapoer Cowek.",
                             tenantId: 9)
                   ]),
        TenantItem(id: 10,
                   name: "Mama Djempol",
                   image: "mamadjempol_img",
                   logo: "mama djempol logo",
                   minPrice: 18000,
                   maxPrice: 30000,
                   tags: ["kategori.Ayam", "kategori.Sapi", "kategori.Ikan", "kategori.Cabe", "kategori.Sayur"],
                   description: "Masakan ala mama yang bikin jempol naik!",
                   foodItems: [
                    FoodItem(name: "Ayam Blackpepper",
                             price: 11000,
                             image: "ayam.blackpepper",
                             tags: [ "kategori.Ayam"],
                             location: "Mama Djempol",
                             foodDescription: "Ayam blackpepper yang dagingnya berkualitas dan segar buatan Mama Djempol.",
                             tenantId: 10),
                    FoodItem(
                        name: "Ayam Asam Manis",
                        price: 11000,
                        image: "Ayam Asam Manis",
                        tags: ["kategori.Ayam"],
                        location: "Mama Djempol",
                        foodDescription: "Ayam goreng dengan saus asam manis segar.",
                        tenantId: 10),
                    FoodItem(
                        name: "Ayam Jamur Kancing",
                        price: 11000,
                        image: "Ayam Jamur Kancing",
                        tags: ["kategori.Ayam"],
                        location: "Mama Djempol",
                        foodDescription: "Ayam lezat dipadukan dengan jamur kancing.",
                        tenantId: 10),
                    FoodItem(
                        name: "Ayam pedas manis",
                        price: 11000,
                        image: "Ayam pedas manis",
                        tags: ["kategori.Ayam"],
                        location: "Mama Djempol",
                        foodDescription: "Perpaduan rasa pedas dan manis dalam ayam pilihan.",
                        tenantId: 10),
                    FoodItem(
                        name: "Terong balado",
                        price: 11000,
                        image: "⁠Terong balado",
                        tags: ["kategori.Sayur"],
                        location: "Mama Djempol",
                        foodDescription: "Terong goreng dengan sambal balado khas.",
                        tenantId: 10),
                    FoodItem(
                        name: "Tumis Capcay",
                        price: 11000,
                        image: "Tumis Capcay",
                        tags: ["kategori.Sayur"],
                        location: "Mama Djempol",
                        foodDescription: "Aneka sayuran segar ditumis dengan bumbu lezat.",
                        tenantId: 10),
                    FoodItem(
                        name: "Tumis toge +tahu",
                        price: 11000,
                        image: "Tumis toge +tahu",
                        tags: ["kategori.Sayur"],
                        location: "Mama Djempol",
                        foodDescription: "Toge dan tahu ditumis sederhana tapi nikmat.",
                        tenantId: 10),
                    FoodItem(
                        name: "Ayam Lada Hitam",
                        price: 11000,
                        image: "Ayam Lada Hitam",
                        tags: ["kategori.Ayam"],
                        location: "Mama Djempol",
                        foodDescription: "Ayam dengan saus lada hitam pedas gurih.",
                        tenantId: 10),
                   ]),
        TenantItem(id: 11,
                   name: "AHZA Snack & Beverage",
                   image: "ahza_img",
                   logo: "ahza logo",
                   minPrice: 3000,
                   maxPrice: 30000,
                   tags: ["kategori.Minuman"],
                   description: "Hidangan spesial dengan cita rasa unik.",
                   foodItems: [
                    FoodItem(name: "Es Teh Tawar",
                             price: 3000,
                             image: "Es Teh Tawar",
                             tags: [ "kategori.Minuman"],
                             location: "AHZA",
                             foodDescription: "Es Teh Tawar segar buatan AHZA.",
                             tenantId: 11),
                    FoodItem(name: "Good Day Merah",
                             price: 4000,
                             image: "Good Day Merah",
                             tags: [ "kategori.Minuman"],
                             location: "AHZA",
                             foodDescription: "Good Day Merah nikat buatan AHZA.",
                             tenantId: 11),
                    FoodItem(name: "Indocafe Coffeemix",
                             price: 4000,
                             image: "Indocafe Coffeemix",
                             tags: [ "kategori.Minuman"],
                             location: "AHZA",
                             foodDescription: "Indocafe Coffeemix nikat buatan AHZA.",
                             tenantId: 11),
                    FoodItem(name: "Jus Sirsak",
                             price: 10000,
                             image: "Jus Sirsak",
                             tags: [ "kategori.Minuman"],
                             location: "AHZA",
                             foodDescription: "Jus Sirsak segar buatan AHZA.",
                             tenantId: 11),
                    FoodItem(name: "Jus Strawberry",
                             price: 10000,
                             image: "Jus Strawberry",
                             tags: [ "kategori.Minuman"],
                             location: "AHZA",
                             foodDescription: "Jus Strawberry segar buatan AHZA.",
                             tenantId: 11),
                    FoodItem(name: "Jus Terong Belanda",
                             price: 10000,
                             image: "Jus Terong Belanda",
                             tags: [ "kategori.Minuman"],
                             location: "AHZA",
                             foodDescription: "Jus Terong Belanda segar buatan AHZA.",
                             tenantId: 11),
                    FoodItem(name: "Jus Alpukat",
                             price: 10000,
                             image: "Jus Alpukat",
                             tags: [ "kategori.Minuman"],
                             location: "AHZA",
                             foodDescription: "Jus Alpukat segar buatan AHZA.",
                             tenantId: 11),
                    FoodItem(name: "Jus Apel",
                             price: 10000,
                             image: "Jus Apel",
                             tags: [ "kategori.Minuman"],
                             location: "AHZA",
                             foodDescription: "Jus Apel segar buatan AHZA.",
                             tenantId: 11),
                    FoodItem(name: "Jus Belimbing",
                             price: 10000,
                             image: "Jus Belimbing",
                             tags: [ "kategori.Minuman"],
                             location: "AHZA",
                             foodDescription: "Jus Belimbing segar buatan AHZA.",
                             tenantId: 11),
                    FoodItem(name: "Jus Buah Naga",
                             price: 10000,
                             image: "Jus Buah Naga",
                             tags: [ "kategori.Minuman"],
                             location: "AHZA",
                             foodDescription: "Jus Buah Naga segar buatan AHZA.",
                             tenantId: 11),
                    FoodItem(name: "Jus Jambu",
                             price: 10000,
                             image: "Jus Jambu",
                             tags: [ "kategori.Minuman"],
                             location: "AHZA",
                             foodDescription: "Jus Jambu segar buatan AHZA.",
                             tenantId: 11),
                    FoodItem(name: "Jus Jeruk",
                             price: 10000,
                             image: "Jus Jeruk",
                             tags: [ "kategori.Minuman"],
                             location: "AHZA",
                             foodDescription: "Jus jeruk segar buatan AHZA.",
                             tenantId: 11),
                    FoodItem(name: "Jus Mangga",
                             price: 10000,
                             image: "Jus Mangga",
                             tags: [ "kategori.Minuman"],
                             location: "AHZA",
                             foodDescription: "Jus Mangga segar buatan AHZA.",
                             tenantId: 11),
                    FoodItem(name: "Jus Melon",
                             price: 10000,
                             image: "Jus Melon",
                             tags: [ "kategori.Minuman"],
                             location: "AHZA",
                             foodDescription: "Jus Melon segar buatan AHZA.",
                             tenantId: 11),
                    FoodItem(name: "Jus Nanas",
                             price: 10000,
                             image: "Jus Nanas",
                             tags: [ "kategori.Minuman"],
                             location: "AHZA",
                             foodDescription: "Jus Nanas segar buatan AHZA.",
                             tenantId: 11),
                    FoodItem(name: "Jus Tomat",
                             price: 10000,
                             image: "Jus Tomat",
                             tags: [ "kategori.Minuman"],
                             location: "AHZA",
                             foodDescription: "Jus Tomat segar buatan AHZA.",
                             tenantId: 11),
                    FoodItem(name: "Kapal Api",
                             price: 4000,
                             image: "Kapal Api",
                             tags: [ "kategori.Minuman"],
                             location: "AHZA",
                             foodDescription: "Kapal Api enak buatan AHZA.",
                             tenantId: 11),
                    FoodItem(name: "Luwak",
                             price: 4000,
                             image: "Luwak",
                             tags: [ "kategori.Minuman"],
                             location: "AHZA",
                             foodDescription: "Luwak enak buatan AHZA.",
                             tenantId: 11),
                    FoodItem(name: "Teh Tawar Panas",
                             price: 3000,
                             image: "Teh Tawar Panas",
                             tags: [ "kategori.Minuman"],
                             location: "AHZA",
                             foodDescription: "Teh Tawar Panas enak buatan AHZA.",
                             tenantId: 11),
                    FoodItem(name: "Ades 1.5L",
                             price: 6000,
                             image: "Ades 1,5L",
                             tags: [ "kategori.Minuman"],
                             location: "AHZA",
                             foodDescription: "Ades 1.5L Segar dari AHZA.",
                             tenantId: 11),
                    FoodItem(name: "Ades",
                             price: 4000,
                             image: "Ades",
                             tags: [ "kategori.Minuman"],
                             location: "AHZA",
                             foodDescription: "Ades Segar dari AHZA.",
                             tenantId: 11),
                    FoodItem(name: "Sprite 250 Ml",
                             price: 4000,
                             image: "Sprite 250 Ml",
                             tags: [ "kategori.Minuman"],
                             location: "AHZA",
                             foodDescription: "Sprite 250 Ml Segar dari AHZA.",
                             tenantId: 11),
                    FoodItem(name: "Fanta 250 Ml",
                             price: 4000,
                             image: "Fanta 250 Ml",
                             tags: [ "kategori.Minuman"],
                             location: "AHZA",
                             foodDescription: "Fanta 250 Ml Segar dari AHZA.",
                             tenantId: 11),
                    FoodItem(name: "Fanta 390 Ml",
                             price: 6000,
                             image: "Fanta 390 Ml",
                             tags: [ "kategori.Minuman"],
                             location: "AHZA",
                             foodDescription: "Fanta 250 Ml Segar dari AHZA.",
                             tenantId: 11),
                    FoodItem(name: "Indomie Double",
                             price: 14000,
                             image: "Indomie Double",
                             tags: [ "kategori.Processed"],
                             location: "AHZA",
                             foodDescription: "Indomie Double lezat segar dari AHZA.",
                             tenantId: 11),
                    FoodItem(name: "Prestine",
                             price: 4000,
                             image: "Prestine",
                             tags: [ "kategori.Minuman"],
                             location: "AHZA",
                             foodDescription: "Prestine Segar dari AHZA.",
                             tenantId: 11),
                    FoodItem(name: "Indomie Double + Telor ",
                             price: 14000,
                             image: "Indomie Double + Telor ",
                             tags: [ "kategori.Processed"],
                             location: "AHZA",
                             foodDescription: "Indomie Double + Telor  lezat segar dari AHZA.",
                             tenantId: 11),
                    FoodItem(name: "Indomie Goreng + Telor ",
                             price: 10000,
                             image: "Indomie Goreng + Telor",
                             tags: [ "kategori.Processed"],
                             location: "AHZA",
                             foodDescription: "Indomie Goreng + Telor lezat segar dari AHZA.",
                             tenantId: 11),
                    FoodItem(name: "Indomie Goreng",
                             price: 7000,
                             image: "Indomie Goreng",
                             tags: [ "kategori.Processed"],
                             location: "AHZA",
                             foodDescription: "Indomie Goreng lezat segar dari AHZA.",
                             tenantId: 11),
                    FoodItem(name: "Indomie Rebus + Telor",
                             price: 10000,
                             image: "Indomie Rebus + Telor",
                             tags: [ "kategori.Processed"],
                             location: "AHZA",
                             foodDescription: "Indomie Rebus + Telor lezat segar dari AHZA.",
                             tenantId: 11),
                    FoodItem(name: "Indomie Rebus",
                             price: 7000,
                             image: "indomie Rebus",
                             tags: [ "kategori.Processed"],
                             location: "AHZA",
                             foodDescription: "indomie Rebus lezat segar dari AHZA.",
                             tenantId: 11),
                   ]),
        TenantItem(id: 12,
                   name: "Mustafa Minang",
                   image: "mustafaminang_img",
                   logo: "minang logo",
                   minPrice: 18000,
                   maxPrice: 30000,
                   tags: ["kategori.Ayam", "kategori.Sapi", "kategori.Ikan", "kategori.Cabe", "kategori.Sayur"],
                   description: "Masakan Minang otentik, pedas dan menggugah selera.",
                   foodItems: [
                    FoodItem(name: "Nasi + Ayam",
                             price: 22000,
                             image: "nasi.ayam.padang",
                             tags: [ "kategori.Ayam",  "kategori.Sayur"],
                             location: "Mustafa Minang",
                             foodDescription: "Paket nasi dan ayam gulai",
                             tenantId: 12),
                    FoodItem(name: "Nasi + Rendang",
                             price: 25000,
                             image: "nasi.rendang.padang",
                             tags: [ "kategori.Sapi", "kategori.Sayur"],
                             location: "Mustafa Minang",
                             foodDescription: "Paket nasi dan rendang sapi",
                             tenantId: 12),
                    FoodItem(name: "Nasi + Dendeng",
                             price: 25000,
                             image: "nasi.dendeng.padang",
                             tags: [ "kategori.Sapi", "kategori.Sayur"],
                             location: "Mustafa Minang",
                             foodDescription: "Paket nasi dan dendeng sapi",
                             tenantId: 12),
                    FoodItem(name: "Nasi + Gulai Tunjang",
                             price: 33000,
                             image: "nasigulaitunjang",
                             tags: [ "kategori.Sapi", "kategori.Sayur"],
                             location: "Mustafa Minang",
                             foodDescription: "Paket nasi dan gulai tunjang",
                             tenantId: 12),
                    FoodItem(name: "Nasi + Gulai Cincang",
                             price: 25000,
                             image: "nasi.gulai.cincang",
                             tags: [ "kategori.Sapi", "kategori.Sayur"],
                             location: "Mustafa Minang",
                             foodDescription: "Paket nasi dan gulai cincang",
                             tenantId: 12),
                    FoodItem(name: "Nasi + Sambal Goreng Ati",
                             price: 23000,
                             image: "nasi.sambal.ati",
                             tags: [ "kategori.Sapi","kategori.Cabe", "kategori.Sayur"],
                             location: "Mustafa Minang",
                             foodDescription: "Ayan bistik yang dagingnya berkualitas dan segar buatan Mustafa Minang.",
                             tenantId: 12),
                    FoodItem(name: "Nasi + Ikan",
                             price: 20000,
                             image: "nasi.padang.ikan",
                             tags: [ "kategori.Sapi", "kategori.Sayur"],
                             location: "Mustafa Minang",
                             foodDescription: "Paket nasi dan ikan",
                             tenantId: 12),
                    FoodItem(name: "Nasi + Perkedel",
                             price: 15000,
                             image: "nasi.perkedel.padang",
                             tags: [ "kategori.Sayur"],
                             location: "Mustafa Minang",
                             foodDescription: "Paket nasi dan perkedel",
                             tenantId: 12),
                    FoodItem(name: "Nasi + Telor",
                             price: 15000,
                             image: "nasi.telor.padang",
                             tags: [ "kategori.Sayur"],
                             location: "Mustafa Minang",
                             foodDescription: "Paket nasi dan telor",
                             tenantId: 12),
                    FoodItem(name: "Nasi + Gulai Otak",
                             price: 25000,
                             image: "nasi.otak.sapi",
                             tags: [ "kategori.Sapi", "kategori.Sayur"],
                             location: "Mustafa Minang",
                             foodDescription: "Paket nasi dan gulai otak",
                             tenantId: 12)
                   ]),
        TenantItem(id: 13,
                   name: "Bakso Jos",
                   image: "baksojos_img",
                   logo: "bakso jos logo",
                   minPrice: 18000,
                   maxPrice: 30000,
                   tags: ["kategori.Ayam", "kategori.Ikan", "kategori.Cabe", "kategori.Sayur"],
                   description: "Bakso kenyal dengan kuah kaldu mantap.",
                   foodItems: [
                    FoodItem(name: "Bakso Urat Komplit",
                             price: 25000,
                             image: "bakso.urat.komplit.baksojos",
                             tags: [ "kategori.Sapi"],
                             location: "Bakso Jos",
                             foodDescription: "Bake urat Komplit dengan daging sapi dan sayur buatan Bakso Jos.",
                             tenantId: 13),
                    FoodItem(name: "Bakso Urat",
                             price: 22000,
                             image:"Bakso Urat",
                             tags: [ "kategori.Sapi",],
                             location: "Bakso Jos",
                             foodDescription: "Bake urat dengan daging sapi dan sayur buatan Bakso Jos.",
                             tenantId: 13),
                    FoodItem(name: "Bakso Rawit",
                             price: 22000,
                             image:"Bakso Rawit",
                             tags: [ "kategori.Sapi",],
                             location: "Bakso Jos",
                             foodDescription: "Bake Rawit dengan daging sapi dan sayur buatan Bakso Jos.",
                             tenantId: 13),
                    FoodItem(name: "Bakso Rawit Komplit",
                             price: 25000,
                             image:"Bakso Rawit",
                             tags: [ "kategori.Sapi",],
                             location: "Bakso Jos",
                             foodDescription: "Bake Rawit Komplit dengan daging sapi dan sayur buatan Bakso Jos.",
                             tenantId: 13),
                    FoodItem(name: "Bakwan Malang Satuan",
                             price: 3000,
                             image:"Bakwan Malang Satuan",
                             tags: [ "kategori.Sapi",],
                             location: "Bakso Jos",
                             foodDescription: "Bakwan Malang Satuan dengan daging sapi dan sayur buatan Bakso Jos.",
                             tenantId: 13),
                    FoodItem(name: "Bakwan Malang Komplit",
                             price: 15000,
                             image:"Bakwan Malang Komplit",
                             tags: [ "kategori.Sapi",],
                             location: "Bakso Jos",
                             foodDescription: "Bakwan Malang Komplit dengan daging sapi dan sayur buatan Bakso Jos.",
                             tenantId: 13),
                    FoodItem(name: "Sup Ikan Kuah Asam",
                             price: 20000,
                             image:"Sup Ikan Kuah Asam",
                             tags: [ "kategori.Ikan","kategori.Sayur"],
                             location: "Bakso Jos",
                             foodDescription: "Sup Ikan Kuah Asam dengan daging sapi dan sayur buatan Bakso Jos.",
                             tenantId: 13),
                    FoodItem(name: "Sup Salmon",
                             price: 25000,
                             image:"Sup Salmon",
                             tags: [ "kategori.Ikan","kategori. sayur"],
                             location: "Bakso Jos",
                             foodDescription: "Sup Salmon dengan ikan dan sayur buatan Bakso Jos.",
                             tenantId: 13),
                    FoodItem(name: "Sup Tom Yum",
                             price: 20000,
                             image:"Sup Tom Yum",
                             tags: [ "kategori.Ikan","kategori. sayur"],
                             location: "Bakso Jos",
                             foodDescription: "Sup Tom Yum dengan ikan dan sayur buatan Bakso Jos.",
                             tenantId: 13),
                    FoodItem(name: "Ikan Dori Goreng Tepung",
                             price: 20000,
                             image:"Ikan Dori Goreng Tepung",
                             tags: [ "kategori.Ikan"],
                             location: "Bakso Jos",
                             foodDescription: "Ikan Dori Goreng Tepung dengan ikan yang di olah buatan Bakso Jos.",
                             tenantId: 13),
                    FoodItem(name: "Sup Ikan",
                             price: 25000,
                             image:"Sup Ikan",
                             tags: [ "kategori.Ikan","kategori.Sayur"],
                             location: "Bakso Jos",
                             foodDescription: "Sup Ikan dengan ikan dan sayur yang di olah buatan Bakso Jos.",
                             tenantId: 13)
                   ]),
        TenantItem(id: 14,
                   name: "Warung Gado-Gado",
                   image: "Warung Gado-Gado",
                   logo: "gadogado.logo",
                   minPrice: 17000,
                   maxPrice: 25000,
                   tags: ["kategori.Sayur", "kategori.Kacang"],
                   description: "Gado Gado Nikmat dan Sehat.",
                   foodItems: [
                    FoodItem(name: "Ketoprak",
                             price: 17000,
                             image:"Ketoprak",
                             tags: ["kategori.Sayur", "kategori.Kacang"],
                             location: "Warung Gado-Gado",
                             foodDescription: "Ketoprak yang nikmat dengan sayuran yang segar dan juga bumbu kacang yang gurihyang di buat oleh Warung Gado Gado.",
                             tenantId: 14),
                    FoodItem(name: "Ketoprak Lontong",
                             price: 20000,
                             image:"Ketoprak Lontong",
                             tags: ["kategori.Sayur", "kategori.Kacang"],
                             location: "Warung Gado-Gado",
                             foodDescription: "Ketoprak Lontong yang nikmat dengan sayuran yang segar dan juga bumbu kacang yang gurih yang di buat oleh Warung Gado Gado.",
                             tenantId: 14),
                    FoodItem(name: "Ketoprak Lontong + Telor",
                             price: 23000,
                             image:"Ketoprak Lontong + Telor",
                             tags: ["kategori.Sayur", "kategori.Kacang"],
                             location: "Warung Gado-Gado",
                             foodDescription: "Ketoprak Lontong + Telor yang nikmat dengan sayuran yang segar dan juga bumbu kacang yang gurih yang di buat oleh Warung Gado Gado.",
                             tenantId: 14),
                    FoodItem(name: "Gado Gado Sayur",
                             price: 23000,
                             image:"Gado Gado Sayur",
                             tags: ["kategori.Sayur", "kategori.Kacang"],
                             location: "Warung Gado-Gado",
                             foodDescription: "Gado Gado Sayur yang nikmat dengan sayuran yang segar dan juga bumbu kacang yang gurih yang di buat oleh Warung Gado Gado.",
                             tenantId: 14),
                    FoodItem(name: "Gado Gado Sayur + Lontong",
                             price: 17000,
                             image:"Gado Gado Sayur + Lontong",
                             tags: ["kategori.Sayur", "kategori.Kacang"],
                             location: "Warung Gado-Gado",
                             foodDescription: "Gado Gado Sayur + Lontong yang nikmat dengan sayuran yang segar dan juga bumbu kacang yang gurih yang di buat oleh Warung Gado Gado.",
                             tenantId: 14),
                    FoodItem(name: "Gado Gado Sayur + Lontong + Telor",
                             price: 25000,
                             image:"Gado Gado Sayur + Lontong + Telor",
                             tags: ["kategori.Sayur", "kategori.Kacang"],
                             location: "Warung Gado-Gado",
                             foodDescription: "Gado Gado Sayur + Lontong + Telor yang nikmat dengan sayuran yang segar dan juga bumbu kacang yang gurih yang di buat oleh Warung Gado Gado.",
                             tenantId: 14)
                   ])
    ]
}
